### ISSUE TITLE
Small changes required for an upcoming Atom release

### ISSUE THREAD

**Issue by maxbrunsfeld** [tswaters/atom-mocha-runner#10]
Hi! Atom will soon be upgrading to a new version of Electron, which will cause some APIs to change.

You'll need to:
- change [this usage](https://github.com/tswaters/atom-mocha-runner/blob/bef761a606ec0b73fe2b580e27e586cbcb77dd97/lib/window.js#L19) of `BrowserWindow.prototype.loadUrl` to `this.window.webContents.loadURL`.
- change `require("ipc")` with `require("electron").ipcRenderer`
- change `require("remote")` with `require("electron").remote`
- change `remote.require("browser-window")` with `remote.BrowserWindow`

There may be other similar small changes required. See [this post](http://electron.atom.io/blog/2015/11/17/electron-api-changes) on the electron blog for more information. And let me know if you need any additional help. Thanks!

**Comment by tswaters** [comment]
Thanks, this is fixed in [v1.2.0](https://github.com/tswaters/atom-mocha-runner/releases/tag/v1.2.0)
