### ISSUE TITLE
Doesn't correctly display test failures within nested describe blocks

### ISSUE THREAD

**Issue by dchambers** [tswaters/atom-mocha-runner#8]
This package seems really good, but if you have a failing test within a nested `describe` block then it's not obvious the tests weren't successful as you don't see any red blocks in the error report (you can only tell by looking at the total fail count which will be non-zero), and it's hard to find the error because each top-level `describe` reports zero failures, so you have to open them all up until you find the culprit.

**Comment by tswaters** [comment]
Thanks for the report -- I'll look into this sometime this weekend.

**Comment by dchambers** [comment]
No rush, and thanks so much for a really nice tool to now have in my kit bag.

**Comment by tswaters** [comment]
Sorry about the wait -- I've fixed this now in 1.1.10

**Comment by dchambers** [comment]
Much appreciated @tswaters :+1:. I'll give this a try later on today...
